version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod

  app:
    build: .
    command: npm start
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    links:
      - mongodb
    depends_on:
      - mongodb