version: '3'
services:
  mongodb:
    image: mongo:latest
    # volumes:
    #   - ./data:/data/db
    ports:
      - 27017:27017
    command: mongod

  app:
    build: .
    command: npm start
    ports:
      - 3000:3000
    # env_file: ./atena-api/.env
    # environment:
    #   - environment=local
    volumes:
      - .:/app
    links:
      - mongodb
    depends_on:
      - mongodb